"""phase 2: optimize schema for nlp and user profiles

Revision ID: 795b833c8fdd
Revises: 
Create Date: 2026-06-24 14:31:40.929204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '795b833c8fdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danmaku_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('danmaku_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('intent_score', sa.Float(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_danmaku_analysis_danmaku_id'), 'danmaku_analysis', ['danmaku_id'], unique=True)
    op.create_index(op.f('ix_danmaku_analysis_id'), 'danmaku_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_danmaku_analysis_task_id'), 'danmaku_analysis', ['task_id'], unique=False)
    op.add_column('danmaku_records', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.add_column('danmaku_records', sa.Column('user_level', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_danmaku_records_user_id'), 'danmaku_records', ['user_id'], unique=False)
    op.drop_column('danmaku_records', 'sentiment_score')
    op.drop_column('danmaku_records', 'keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('danmaku_records', sa.Column('keywords', sqlite.JSON(), nullable=True))
    op.add_column('danmaku_records', sa.Column('sentiment_score', sa.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_danmaku_records_user_id'), table_name='danmaku_records')
    op.drop_column('danmaku_records', 'user_level')
    op.drop_column('danmaku_records', 'user_id')
    op.drop_index(op.f('ix_danmaku_analysis_task_id'), table_name='danmaku_analysis')
    op.drop_index(op.f('ix_danmaku_analysis_id'), table_name='danmaku_analysis')
    op.drop_index(op.f('ix_danmaku_analysis_danmaku_id'), table_name='danmaku_analysis')
    op.drop_table('danmaku_analysis')
    # ### end Alembic commands ###
