import asyncio
import os
import re
from typing import Dict, List

from app.scraper.base import BaseScraper


class SphScraper(BaseScraper):
    def __init__(
        self,
        room_id: str,
        event_name: str | None = None,
        car_brand: str | None = None,
        car_model: str | None = None,
        event_id: str | None = None,
        headless: bool = True,
    ):
        # We look for a storage state file that should be generated by a `login` command
        auth_file = os.path.join(os.getcwd(), "auth", "sph_state.json")
        storage_state = auth_file if os.path.exists(auth_file) else None
        
        super().__init__(
            room_id=room_id,
            platform="sph",
            event_name=event_name,
            car_brand=car_brand,
            car_model=car_model,
            event_id=event_id,
            headless=headless,
            storage_state=storage_state,
        )
        self.url = f"https://channels.weixin.qq.com/platform/live/{room_id}" # or appropriate URL format
        # Alternatively, we can use the viewer link. The exact format might vary.
        # Often it's https://channels.weixin.qq.com/web/live/{room_id} or similar.
        # We will use the web viewer url.
        self.url = f"https://channels.weixin.qq.com/web/live/{room_id}"
        self.danmaku_buffer: List[Dict[str, str]] = []
        self.last_msg_texts: set[str] = set()
        self.latest_online_count = 0

    async def _get_online_count(self) -> int:
        """
        尝试从页面 DOM 中提取实时观看人数或热度。
        """
        try:
            # 视频号通常在某个元素里显示 "xxx人看过"
            # 具体选择器可能需要根据实际页面调整
            # 假设有一个包含 "看过" 文本的元素
            elements = await self.page.query_selector_all("span, div")
            for el in elements:
                text = await el.inner_text()
                if text and "看过" in text:
                    # 尝试提取数字
                    match = re.search(r'([\d\.]+万?)', text)
                    if match:
                        num_str = match.group(1)
                        if "万" in num_str:
                            return int(float(num_str.replace("万", "")) * 10000)
                        return int(num_str)
        except Exception:
            pass
        return 0

    async def run_loop(self):
        """循环读取 DOM 中的弹幕并批量入库"""
        await self.start()

        if not self.storage_state:
            print(f"[{self.platform}] 警告: 未找到登录凭证(auth/sph_state.json)，视频号可能需要扫码登录。建议先运行 `login sph` 命令。")

        try:
            print(f"[{self.platform}] 正在打开视频号直播间: {self.url}")
            await self.page.goto(self.url, wait_until="domcontentloaded")
            # 等待页面加载一段时间
            await asyncio.sleep(5)
        except Exception as e:
            print(f"[{self.platform}] 打开页面失败: {e}")
            await self.stop()
            return

        while self.is_running:
            try:
                # 1. 解析弹幕
                # 视频号 web 端的弹幕 DOM 结构可能会变，这里提供一个常见的推测结构
                # 通过在页面执行 JS 来获取当前的所有弹幕
                new_danmakus = await self.page.evaluate('''() => {
                    // 寻找包含弹幕的容器，这需要根据实际 DOM 结构调整
                    // 假设类名中包含 message 或 chat 相关的词
                    const items = document.querySelectorAll('div[class*="message"], div[class*="chat-item"]');
                    const results = [];
                    items.forEach(item => {
                        // 提取用户名和内容，这里假设简单的结构
                        const nameEl = item.querySelector('span[class*="name"], div[class*="name"]');
                        const contentEl = item.querySelector('span[class*="content"], div[class*="content"]');
                        if (nameEl && contentEl) {
                            results.push({
                                user_name: nameEl.innerText.trim(),
                                content: contentEl.innerText.trim()
                            });
                        } else {
                            // 兜底: 如果没有明确的结构，尝试解析纯文本，比如 "张三: 遥遥领先"
                            const text = item.innerText.trim();
                            if (text.includes(':')) {
                                const parts = text.split(':');
                                if (parts.length >= 2) {
                                    results.push({
                                        user_name: parts[0].trim(),
                                        content: parts.slice(1).join(':').trim()
                                    });
                                }
                            }
                        }
                    });
                    return results;
                }''')
                
                valid_danmakus = []
                for msg in new_danmakus:
                    user_name = msg.get("user_name", "")
                    content = msg.get("content", "")
                    if not user_name or not content:
                        continue
                        
                    # 简单防重: 根据用户名+内容拼接的哈希去重
                    msg_hash = f"{user_name}::{content}"
                    if msg_hash not in self.last_msg_texts:
                        self.last_msg_texts.add(msg_hash)
                        valid_danmakus.append({
                            "user_name": user_name,
                            "content": content
                        })
                
                # 维护去重池大小
                if len(self.last_msg_texts) > 2000:
                    # 简单清理策略：清空一半
                    self.last_msg_texts = set(list(self.last_msg_texts)[-1000:])
                    
                if valid_danmakus:
                    self.danmaku_buffer.extend(valid_danmakus)
                    print(f"[{self.platform}] 抓取到 {len(valid_danmakus)} 条新弹幕")

                # 2. 解析热度
                online_count = await self._get_online_count()
                if online_count > 0:
                    self.latest_online_count = online_count

                # 3. 批量落库逻辑: 累计 20 条弹幕后写一次
                if len(self.danmaku_buffer) >= 20:
                    self._flush_to_db(self.latest_online_count)

            except Exception as e:
                print(f"[{self.platform}] 抓取循环异常: {e}")
            
            # 每 2 秒抓取一次 DOM
            await asyncio.sleep(2)

        self._flush_to_db(current_online_count=self.latest_online_count)
        await self.stop()

    def _flush_to_db(self, current_online_count: int):
        """将缓冲区的弹幕写入数据库"""
        try:
            self.flush_danmaku_records(
                danmakus=self.danmaku_buffer,
                online_count=current_online_count,
                like_count=0,
            )
            if self.danmaku_buffer:
                print(f"[{self.platform}] 成功将 {len(self.danmaku_buffer)} 条弹幕写入数据库，当前热度: {current_online_count}")
            self.danmaku_buffer.clear()
        except Exception as e:
            print(f"[{self.platform}] 落库失败: {e}")
